export const DOT_LENGTH = 100
export const PIXEL_DOT_LENGTH = 20
export const DASH_LENGTH = DOT_LENGTH * 3
export const PIXEL_DASH_LENGTH = PIXEL_DOT_LENGTH * 3
export const INTRA_CHAR_SPACE = DOT_LENGTH
export const INTER_CHAR_SPACE = DASH_LENGTH
export const WORD_SPACE = DASH_LENGTH * 7
export const PIXEL_WORD_SPACE = PIXEL_DASH_LENGTH * 7

export const ERROR_MARGIN_DOT = 0.50
export const ERROR_MARGIN_DASH = 0.20